# Generated by Django 3.2.6 on 2021-10-19 09:09

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nomi:')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyasi',
            },
        ),
        migrations.CreateModel(
            name='OurContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutteam', models.TextField(blank=True, null=True)),
                ('app_store', models.CharField(max_length=255, verbose_name='App Store')),
                ('telegram', models.CharField(max_length=255, verbose_name='Telegram')),
                ('facebook', models.CharField(max_length=255, verbose_name='Facebook')),
                ('youtube', models.CharField(max_length=255, verbose_name='You Tube')),
                ('logo', models.FileField(max_length=255, upload_to='', verbose_name='Logo')),
                ('play_market', models.CharField(max_length=255, verbose_name='Play Market')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=products.models.slider_path, verbose_name='Rasmi:')),
            ],
            options={
                'verbose_name': 'Slayd',
                'verbose_name_plural': 'Slaydlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mahsulot haqida batafsil:')),
                ('cost', models.FloatField(verbose_name='Narxi :')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path, verbose_name='Rasmi')),
                ('video', models.FileField(blank=True, null=True, upload_to=products.models.product_video_path, verbose_name='Videosi:')),
                ('count_in_store', models.IntegerField(default=0, verbose_name='Zaxiradagi mahsulotlar soni:')),
                ('sold_count', models.IntegerField(default=0, verbose_name='Sotilgan maxsulotlar soni:')),
                ('unsold_count', models.IntegerField(default=0, verbose_name='Sotilmagan mahsulotlar soni:')),
                ('onhold_count', models.IntegerField(default=0, verbose_name="Kutish bo'limidagilar soni:")),
                ('trend', models.BooleanField(default=False, verbose_name='Modami:')),
                ('unit', models.TextField(choices=[('tonna', 'tonna'), ('kg', 'kg'), ('gramm', 'gramm'), ('pachka', 'pachka'), ('dona', 'dona')], default='dona', verbose_name='mahsulot birligi:')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('has_discount', models.BooleanField(default=False)),
                ('discount', models.FloatField(default=0, verbose_name='Chegirma')),
                ('discount_unit', models.TextField(choices=[('%', '%'), ("so'm", "so'm")], default='%', verbose_name='Chegirma birligi')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Kategoriyasi:')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Yetkazildi', 'Yetkazildi'), ('Yetkazilmadi', 'Yetkazilmadi')], default='Pending')),
                ('quantity', models.IntegerField(default=1, verbose_name='Mahsulotlar miqdori:')),
                ('total', models.FloatField(default=0, verbose_name='Mahsulotlarning umumiy summasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyurtmalar', to='products.product')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
